apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus 
        image: prom/prometheus  
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus
          mountPath: /prometheus
        ports:
        - containerPort: 9090
      volumes:
      - name: config 
        configMap:
          name: config
      - name: prometheus
        persistentVolumeClaim:
          claimName: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus 
spec:
  ports:
  - port: 9090 
    targetPort: 9090 
  type: LoadBalancer
  selector:
    app: prometheus 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
